version: '3'
services: 
  frontend:
    image: nginx:latest
    ports:
      - 80:80
    volumes:
      - ./frontend:/usr/share/nginx/html
    networks:
      - mynetwork
  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    environment:
      - DB_HOST=database
    depends_on:
      - database
    networks:
      - mynetwork
  
  database:
    image: mysql
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=prabin123
      - MYSQL_DATABASE=DB
    volumes:
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
      - dbdata:/var/lib/mysql
    networks:
      - mynetwork

volumes:
  frontend:
  dbdata:

networks:
  mynetwork:
    driver: bridge
